#!/bin/bash
# This repository copy is intentionally not the production installer.
#
# The real Linux agent installer is generated by the hub and served from:
#
#   https://<hub-host>/install.sh
#
# It is generated at runtime because it embeds the current hub URL, install
# token contract, CA bootstrap, systemd unit, and rollback helper expected by
# the running hub.

set -euo pipefail

cat >&2 <<'EOF'
BloxOS agent installer is served by the running hub.

From the dashboard, click Add Machine and run the generated command, or call:

  export BLOXOS_HUB=wss://<hub-host>/ws/agent
  export BLOXOS_TOKEN=<one-time-token>
  curl -fsSL https://<hub-host>/install.sh | bash

EOF

exit 1
