package main

import (
	"fmt"
	"strings"
)

// installTokenResponse is the complete authenticated bootstrap contract. Every
// command is generated by the hub from PUBLIC_URL; the browser never derives
// an authority or interpolates the enrollment token itself.
type installTokenResponse struct {
	Token string `json:"token"`
	// Command is the Linux one-liner: fetch JoinURL and run it once. See
	// join.go for how the fetch is authenticated.
	Command string `json:"command"`
	// AdvancedCommand is the complete verbose Linux bootstrap, the exact
	// text GET JoinURL serves, for operators who want to read what will run
	// or who cannot use the join link. Before join links existed this was
	// the value of Command.
	AdvancedCommand string `json:"advanced_command"`
	JoinURL         string `json:"join_url"`
	// JoinPin is the sha256// SPKI pin Command carries when the hub is
	// behind a private CA; empty for publicly trusted TLS and for http.
	JoinPin        string `json:"join_pin,omitempty"`
	WindowsCommand string `json:"windows_command"`
	CAURL          string `json:"ca_url"`
	CASHA256       string `json:"ca_sha256"`
	ExpiresAt      string `json:"expires_at"`
}

// windowsReenrollmentResponse is the contract for a machine-bound Windows
// re-enrollment token. Unlike installTokenResponse it carries no Linux
// command (this flow is Windows-only) and echoes machine_id so the caller
// can confirm the token was minted for the machine it asked about.
type windowsReenrollmentResponse struct {
	MachineID      string `json:"machine_id"`
	Token          string `json:"token"`
	WindowsCommand string `json:"windows_command"`
	CAURL          string `json:"ca_url"`
	CASHA256       string `json:"ca_sha256"`
	ExpiresAt      string `json:"expires_at"`
}

func shellSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func powershellSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func buildLinuxInstallCommand(httpBase, wsBase, token, caURL, caSHA256 string) string {
	return fmt.Sprintf(`set -euo pipefail
HUB_HTTP=%s
HUB_WS=%s
TOKEN=%s
CA_URL=%s
CA_SHA256=%s
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT
CA_ARGS=()
CA_ENV=()
if [[ -n "$CA_SHA256" ]]; then
  CA_PATH=/etc/bloxos/ca.crt
  if sudo test -f "$CA_PATH"; then
    ACTUAL_CA_SHA=$(sudo sha256sum "$CA_PATH" | awk '{print $1}')
    if [[ "$ACTUAL_CA_SHA" != "$CA_SHA256" ]]; then
      echo "Existing CA fingerprint mismatch; refusing to replace $CA_PATH" >&2
      exit 1
    fi
    echo "Reusing fingerprint-verified CA at $CA_PATH"
  else
    TMP_CA="$TMP_DIR/ca.crt"
    curl --proto '=https' --tlsv1.2 -fsSLk "$CA_URL" -o "$TMP_CA"
    ACTUAL_CA_SHA=$(sha256sum "$TMP_CA" | awk '{print $1}')
    if [[ "$ACTUAL_CA_SHA" != "$CA_SHA256" ]]; then
      echo "CA fingerprint mismatch; expected $CA_SHA256, got $ACTUAL_CA_SHA" >&2
      exit 1
    fi
    sudo install -d -o root -g root -m 0755 /etc/bloxos
    sudo install -o root -g root -m 0644 "$TMP_CA" "$CA_PATH"
  fi
  CA_ARGS=(--cacert "$CA_PATH")
  CA_ENV=(BLOXOS_CA_CERT="$CA_PATH" BLOXOS_CA_SHA256="$CA_SHA256")
fi
INSTALLER="$TMP_DIR/install.sh"
if [[ "$HUB_HTTP" == https://* ]]; then
  curl --proto '=https' --tlsv1.2 -fsSL "${CA_ARGS[@]}" "$HUB_HTTP/install.sh" -o "$INSTALLER"
else
  echo "WARNING: direct HTTP bootstrap is unencrypted and is intended only for loopback or isolated test networks." >&2
  curl -fsSL "$HUB_HTTP/install.sh" -o "$INSTALLER"
fi
env BLOXOS_HUB="$HUB_WS" BLOXOS_TOKEN="$TOKEN" "${CA_ENV[@]}" bash "$INSTALLER"`,
		shellSingleQuote(httpBase), shellSingleQuote(wsBase), shellSingleQuote(token),
		shellSingleQuote(caURL), shellSingleQuote(caSHA256))
}

func buildWindowsInstallCommand(httpBase, wsBase, token, caURL, caSHA256 string, forceReenroll bool) string {
	httpWarning := ""
	if strings.HasPrefix(httpBase, "http://") {
		httpWarning = `Write-Warning "Direct HTTP bootstrap is unencrypted and is intended only for loopback or isolated test networks."`
	}
	installerArgs := ""
	if forceReenroll {
		installerArgs = " -ForceReenroll"
	}
	return fmt.Sprintf(`$ErrorActionPreference = 'Stop'
$HubHttp = %s
$HubWs = %s
$Token = %s
$CaUrl = %s
$ExpectedCaSha = %s
$CredDir = "C:\Windows\System32\config\systemprofile\.bloxos"
$CaPath = Join-Path $CredDir "ca.crt"
$TempDir = Join-Path ([IO.Path]::GetTempPath()) ("bloxos-bootstrap-" + [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $TempDir | Out-Null
try {
    if ($ExpectedCaSha) {
        if (Test-Path -LiteralPath $CaPath) {
            $ActualCaSha = (Get-FileHash -Algorithm SHA256 -LiteralPath $CaPath).Hash.ToLower()
            if ($ActualCaSha -ne $ExpectedCaSha.ToLower()) { throw "Existing CA fingerprint mismatch; refusing to replace $CaPath" }
            Write-Host "Reusing fingerprint-verified CA at $CaPath"
        } else {
            $TempCa = Join-Path $TempDir "ca.crt"
            & curl.exe --ssl-revoke-best-effort -ksfL -o $TempCa $CaUrl
            if ($LASTEXITCODE -ne 0) { throw "CA download failed (curl exit $LASTEXITCODE)" }
            $ActualCaSha = (Get-FileHash -Algorithm SHA256 -LiteralPath $TempCa).Hash.ToLower()
            if ($ActualCaSha -ne $ExpectedCaSha.ToLower()) { throw "CA fingerprint mismatch; expected $ExpectedCaSha, got $ActualCaSha" }
            New-Item -ItemType Directory -Path $CredDir -Force | Out-Null
            Move-Item -LiteralPath $TempCa -Destination $CaPath
        }
    }
    $Installer = Join-Path $TempDir "install.ps1"
    if ($ExpectedCaSha) {
        & curl.exe --ssl-revoke-best-effort --cacert $CaPath -sfL -o $Installer "$HubHttp/install.ps1"
    } else {
        %s
        & curl.exe --ssl-revoke-best-effort -sfL -o $Installer "$HubHttp/install.ps1"
    }
    if ($LASTEXITCODE -ne 0) { throw "Installer download failed (curl exit $LASTEXITCODE)" }
    $env:BLOXOS_HUB = $HubWs
    $env:BLOXOS_TOKEN = $Token
    $env:BLOXOS_CA_SHA256 = $ExpectedCaSha
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Installer%s
    if ($LASTEXITCODE -ne 0) { throw "Installer failed (exit $LASTEXITCODE)" }
} finally {
    Remove-Item -LiteralPath $TempDir -Recurse -Force -ErrorAction SilentlyContinue
}`,
		powershellSingleQuote(httpBase), powershellSingleQuote(wsBase), powershellSingleQuote(token),
		powershellSingleQuote(caURL), powershellSingleQuote(caSHA256), httpWarning, installerArgs)
}
